### PR TITLE
[Validation Package] Allow validation data to be set directly from an EntityInterface

### PR DESCRIPTION
**Pull request by adelowo**
This PR allows validation data to be set from a `DataEntity` (or `EntityInterface` to be precise)....

Usecase = >

- Currently 

```php

$data = [];
$data[self::ARGS_FULL_NAME] = $this->argument(self::ARGS_FULL_NAME);
$data[self::ARGS_MONIKER] = $this->argument(self::ARGS_MONIKER);
$data[self::ARGS_EMAIL] = $this->argument(self::ARGS_EMAIL);

$transformedData = new SomeDataEntity($data);

$val->setData($transformedData->getFields());

//Do something else with $transformedData
```

- This PR =>

```php
$validator = $validator->withDataEntity($transformedData);
```

Just sugar syntax, but i have found myself this past hour filling an `EntityInterface` and passing it to the validator.

### CODE REVIEW

**Comment by adelowo** [comment]
I don't get why coverage reduced :1234:

**Comment by wolfy-j** [comment]
Few comments:
1) "with" prefix usually used to represent immutable methods, will lead to confusion
2) I'm not sure if it's a good idea to couple validator (and validator interface) an entity as this is parts of different domain

ValidatesEntity combines them together as implementation, but joining this two abstractions on highest level will create higher coupling. 

Another option is too make setData method accept entity directly. Let me think about it till next week.

**Comment by adelowo** [comment]
Alright, but at worse, `setData` should be able to work with an array or an `EntityInterface`

**Comment by wolfy-j** [comment]
Yes it should. http://prntscr.com/f261nc If it's not, you just found a bug :)

**Comment by wolfy-j** [comment]
Actually, it should be working with ArrayAccess which is implemented by all entities but not in the interface.  I will correct that.

**Comment by adelowo** [comment]
I missed noticing it accepts `\ArrayAccess`..

**Comment by wolfy-j** [comment]
Well, EntityInteface is not necessary ArrayAccess so you had a fair point. I created a new branch, let's wait for CI.

**Comment by wolfy-j** [comment]
https://github.com/spiral/spiral/tree/feature/validate-entity

**Comment by wolfy-j** [comment]
BTW, there is a slight chance that cache will work as well now, Validator itself caches errors IF data not changed. Regarding #180

**Comment by adelowo** [comment]
Ok, i am just going to pull that branch and test it out

**Comment by wolfy-j** [comment]
Cool, i included your test as well :)

**Comment by adelowo** [comment]
Closed by #182

**Pull request closed without merging**
